
# https://msmobilecenter.visualstudio.com/Mobile-Center/_build/results?buildId=662289
#
# Triggers are configured in the UI
pool:
  vmImage: 'macOS-10.14'

steps:

- script: ruby -v
  displayName: "ruby version"

- script: xcrun -f xcodebuild
- script: xcrun xcodebuild -version
- script: ls -al /Applications

- script: |
    echo "install: --no-document --env-shebang" > ~/.gemrc
    echo "update:  --no-document --env-shebang" >> ~/.gemrc
  displayName: "install .gemrc"

- script: scripts/ci/jenkins/simctl.sh
  displayName: "ensure CoreSimulator ready"

- script: gem update --system
  displayName: "update ruby gems executable - aka 'gem'"

- script: gem uninstall -Vax --force --no-abort-on-dependent run_loop
  displayName: "uninstall run_loop gem"

- script: |
    gem install bundler
    bundle install --retry=3 --jobs=4
  displayName: "install bundler and gems"

- script: rake install
  displayName: "install run_loop"

- script: bundle exec run-loop simctl manage-processes
  displayName: "manage CoreSimulator processes"

#- script: bundle exec rspec spec/lib
#  displayName: "unit tests"
#
#- script: scripts/ci/jenkins/test/cli.sh
#  displayName: "cli tests"

- script: scripts/ci/jenkins/test/integration.sh
  displayName: "integration tests"

